"""
Dataset de entrenamiento para el extractor de síntomas.
Generado automáticamente a partir del dataset de evaluación.
"""

TRAINING_DATA = [
    {"text": "Sí, me duele bastante cuando lo toco.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "No me duele para nada, no siento nada.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Tengo algo de molestia cuando presiono la zona.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "A veces arde un poco, sobre todo por las noches.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "No siento nada especial, está ahí pero sin dolor.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Para nada, no hay ningún tipo de dolor.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Me escuece un poco si me pongo ropa ajustada.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Me da pinchazos fuertes de vez en cuando.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "No experimento ninguna molestia al presionar.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Es un dolor sordo pero constante.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Siento como que me quema la piel por esa zona.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Afortunadamente no me duele nada.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Está muy sensible al roce, duele.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "No me ha dolido nunca, ni siquiera al principio.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Siento un latido doloroso en el lunar.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Nada de dolor, cero molestias.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Sí, me pica mucho, especialmente por la tarde.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "No me pica, nunca he notado picor.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Tengo comezón de vez en cuando, no siempre.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "A veces pica un poco, sí.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Sin picor, todo normal en esa zona.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "La verdad es que no me rasco nunca, no pica.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Siento una necesidad imperiosa de rascarme.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "No tengo comezón, está muy tranquila la zona.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Me pica horrores por la noche.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Es un picor insoportable a ratos.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "No noto que me pique en absoluto.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Siento como hormigueo y picor constante.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Sin rastro de picor ni escozor.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Me dan ganas de rascarme todo el tiempo.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Ni me pica ni me molesta.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Me pica bastante si sudo mucho.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Sí, ha crecido bastante en los últimos meses.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "No, sigue siendo del mismo tamaño que siempre.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Me parece que está más grande que antes.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "Creo que no ha cambiado, lo veo igual que siempre.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Ha aumentado de tamaño notablemente este año.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "Era más pequeño cuando era niño, ahora es más grande.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "Es idéntico a cuando me salió, no ha variado nada.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Se ha vuelto mucho más abultado y grande.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "Sigue exactamente igual que hace diez años.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Noto que los bordes se están expandiendo.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "Ha duplicado su tamaño en apenas un mes.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "No ha crecido ni un milímetro, está igual.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Antes era un punto pequeño y ahora es una mancha.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "Su tamaño es constante, no ha variado nada.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Creo que está creciendo hacia fuera.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "No ha cambiado de forma ni de tamaño.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Sí, una vez sangró cuando me lo rasqué.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 1, "color": 0}},
    {"text": "No, nunca ha sangrado en ningún momento.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "A veces sangra un poquito, sin causa aparente.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 1, "color": 0}},
    {"text": "No ningún sangrado, está completamente seco.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Ha sangrado dos veces estas semanas.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 1, "color": 0}},
    {"text": "Jamás ha soltado sangre ni nada parecido.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Amanecí con la sábana manchada de sangre.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 1, "color": 0}},
    {"text": "No sangra aunque se me enganche con la ropa.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Suelto un poco de líquido con sangre a veces.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 1, "color": 0}},
    {"text": "Se le ha hecho una costra de sangre.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 1, "color": 0}},
    {"text": "Ningún episodio de sangrado hasta la fecha.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Sangró espontáneamente ayer por la tarde.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 1, "color": 0}},
    {"text": "Está muy seco, no sangra nunca.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Noto que supura un poco de sangre.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 1, "color": 0}},
    {"text": "No ha sangrado ni una sola vez.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "A veces mancho el apósito de sangre.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 1, "color": 0}},
    {"text": "Sí, se ha oscurecido bastante, antes era más claro.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 1}},
    {"text": "No ha cambiado de color, sigue igual.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Tiene colores diferentes, como manchas dentro del lunar.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 1}},
    {"text": "El color es el mismo de siempre, uniforme y marrón.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Cambió de color, ahora tiene partes rojizas.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 1}},
    {"text": "Está mucho más negro que al principio.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 1}},
    {"text": "No noto ninguna variación cromática, está igual.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Tiene un borde azulado que antes no tenía.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 1}},
    {"text": "Mantiene su tono marrón uniforme de siempre.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Se ha vuelto bicolor, marrón y negro.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 1}},
    {"text": "Están apareciendo zonas blancas dentro.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 1}},
    {"text": "No ha habido ningún cambio en la pigmentación.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Está mucho más rojizo que la semana pasada.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 1}},
    {"text": "El color es el mismo, no ha mutado.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Se ha puesto muy oscuro, casi negro azabache.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 1}},
    {"text": "Su tonalidad sigue siendo la misma.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Me pica y también ha cambiado de color, está más oscuro.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 1}},
    {"text": "Duele un poco y sangró el otro día.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 1, "color": 0}},
    {"text": "No duele, no pica y no ha cambiado de tamaño.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Creció bastante y lo noto desde hace 6 semanas.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "No siento dolor ni picor, pero sí noto que ha crecido mucho.", "labels": {"dolor": 0, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 0}},
    {"text": "Está más grande, más oscuro y además me duele.", "labels": {"dolor": 1, "picor": 0, "tamaño": 1, "sangrado": 0, "color": 1}},
    {"text": "Sí.", "labels": {"dolor": 1, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "No.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Un poquito nada más.", "labels": {"dolor": 0, "picor": 1, "tamaño": 0, "sangrado": 0, "color": 0}},
    {"text": "Nunca.", "labels": {"dolor": 0, "picor": 0, "tamaño": 0, "sangrado": 0, "color": 0}},
]
