"""
Training dataset for the symptom extractor.
This data is used to train the MultinomialNB classifier via the train_symptom_extractor() function.
"""

TRAINING_DATA = [
    # --- PAIN ---
    {"text": "Yes, it hurts quite a bit when I touch it.", "labels": {"pain": 1, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It doesn't hurt at all, I feel nothing.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I have some discomfort when I press the area.", "labels": {"pain": 1, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "Sometimes it burns a little, especially at night.", "labels": {"pain": 1, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I don't feel anything special, it's there but without pain.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "Not at all, there is no type of pain.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It stings a bit if I wear tight clothes.", "labels": {"pain": 1, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I get sharp stabs from time to time.", "labels": {"pain": 1, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I don't experience any discomfort when pressing.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It's a dull but constant pain.", "labels": {"pain": 1, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I feel like it burns my skin in that area.", "labels": {"pain": 1, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "Fortunately it doesn't hurt at all.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It's very sensitive to touch, it hurts.", "labels": {"pain": 1, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It has never hurt me, not even at the beginning.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I feel a painful throb in the mole.", "labels": {"pain": 1, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "No pain at all, zero discomfort.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},

    # --- ITCHING ---
    {"text": "Yes, it itches a lot, especially in the afternoon.", "labels": {"pain": 0, "itching": 1, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It doesn't itch, I've never noticed itching.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I have itching from time to time, not always.", "labels": {"pain": 0, "itching": 1, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "Sometimes it itches a bit, yes.", "labels": {"pain": 0, "itching": 1, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "No itching, everything normal in that area.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "Truth is I never scratch, it doesn't itch.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I feel an overwhelming need to scratch.", "labels": {"pain": 0, "itching": 1, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I don't have itching, the area is very calm.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It itches horribly at night.", "labels": {"pain": 0, "itching": 1, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It's an unbearable itch at times.", "labels": {"pain": 0, "itching": 1, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I don't notice it itching at all.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I feel like tingling and constant itching.", "labels": {"pain": 0, "itching": 1, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "No trace of itching or burning.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It makes me want to scratch all the time.", "labels": {"pain": 0, "itching": 1, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It doesn't itch nor bother me.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It itches a lot if I sweat too much.", "labels": {"pain": 0, "itching": 1, "size": 0, "bleeding": 0, "color": 0}},

    # --- SIZE ---
    {"text": "Yes, it has grown quite a bit in recent months.", "labels": {"pain": 0, "itching": 0, "size": 1, "bleeding": 0, "color": 0}},
    {"text": "No, it's still the same size as always.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I think it's larger than before.", "labels": {"pain": 0, "itching": 0, "size": 1, "bleeding": 0, "color": 0}},
    {"text": "I don't think it has changed, I see it the same as always.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It has increased in size notably this year.", "labels": {"pain": 0, "itching": 0, "size": 1, "bleeding": 0, "color": 0}},
    {"text": "It was smaller when I was a child, now it's larger.", "labels": {"pain": 0, "itching": 0, "size": 1, "bleeding": 0, "color": 0}},
    {"text": "It's identical to when I got it, it hasn't varied at all.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It has become much bulkier and larger.", "labels": {"pain": 0, "itching": 0, "size": 1, "bleeding": 0, "color": 0}},
    {"text": "It remains exactly the same as ten years ago.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I notice that the edges are expanding.", "labels": {"pain": 0, "itching": 0, "size": 1, "bleeding": 0, "color": 0}},
    {"text": "It has doubled its size in just a month.", "labels": {"pain": 0, "itching": 0, "size": 1, "bleeding": 0, "color": 0}},
    {"text": "It hasn't grown even a millimeter, it's the same.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "Before it was a small point and now it's a spot.", "labels": {"pain": 0, "itching": 0, "size": 1, "bleeding": 0, "color": 0}},
    {"text": "Its size is constant, it hasn't changed at all.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I think it's growing outwards.", "labels": {"pain": 0, "itching": 0, "size": 1, "bleeding": 0, "color": 0}},
    {"text": "It hasn't changed shape or size.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},

    # --- BLEEDING ---
    {"text": "Yes, once it bled when I scratched it.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 1, "color": 0}},
    {"text": "No, it has never bled at any time.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "Sometimes it bleeds a little bit, for no apparent reason.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 1, "color": 0}},
    {"text": "No bleeding at all, it's completely dry.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It has bled twice these weeks.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 1, "color": 0}},
    {"text": "It has never released blood or anything like that.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I woke up with the sheet stained with blood.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 1, "color": 0}},
    {"text": "It doesn't bleed even if it gets caught in clothes.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I release a little bit of liquid with blood sometimes.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 1, "color": 0}},
    {"text": "It has formed a blood scab.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 1, "color": 0}},
    {"text": "No episodes of bleeding to date.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It bled spontaneously yesterday afternoon.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 1, "color": 0}},
    {"text": "It's very dry, it never bleeds.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "I notice it oozes a bit of blood.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 1, "color": 0}},
    {"text": "It hasn't bled even once.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "Sometimes I stain the dressing with blood.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 1, "color": 0}},

    # --- COLOR ---
    {"text": "Yes, it has darkened quite a bit, it used to be lighter.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 1}},
    {"text": "It hasn't changed color, it's the same.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It has different colors, like spots inside the mole.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 1}},
    {"text": "The color is the same as always, uniform and brown.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It changed color, now it has reddish parts.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 1}},
    {"text": "It's much blacker than at the beginning.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 1}},
    {"text": "I don't notice any chromatic variation, it's the same.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It has a bluish edge that it didn't have before.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 1}},
    {"text": "It maintains its uniform brown tone as always.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "It has become bicolor, brown and black.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 1}},
    {"text": "Never.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "Yes.", "labels": {"pain": 1, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
    {"text": "No.", "labels": {"pain": 0, "itching": 0, "size": 0, "bleeding": 0, "color": 0}},
]
